# Generated by Django 5.1.3 on 2024-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendTi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
