# Generated by Django 5.1.3 on 2024-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendTi', '0002_manual_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
