# Generated by Django 5.1.3 on 2024-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendTi', '0003_alter_manual_url_alter_material_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='foto3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
