# Generated by Django 5.1.3 on 2025-04-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendTi', '0004_componente_descripcion_componente_foto3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backendTi.usuario')),
            ],
            bases=('backendTi.usuario',),
        ),
    ]
